export type Row = Record<string, string | number | boolean | null>;
export type Settings = { distro:string;cliPath:string;session:string;accelerator:string;basePath:string;checkpointPath:string;processedPath:string;rawPath:string;driveOutputs:string;persistDrive:boolean;theme:'dark'|'light' };
export type Metrics = {accuracy:number;balanced_accuracy:number;macro_precision:number;macro_recall:number;macro_f1:number;weighted_f1:number;cohen_kappa:number|null;test_epochs:number;test_subjects?:number};
export type RunManifest = {id:string;name:string;kind:string;status:string;createdAt:string;sourceRun?:string;settings?:Settings;recordings:string[];step:string;progress:number;error?:string;remoteRoot?:string;remotePid?:number;driveBundle?:string;transferError?:string;result?:Record<string,unknown>;epochMetrics?:Record<string,number>};
export type Artifact={path:string;bytes:number;type:string};
export type SignalData={recording_id:string;epoch_index:number;start_seconds?:number;channels:string[];raw?:number[][];processed:number[][];raw_sampling_hz?:number;processed_sampling_hz:number;raw_unit?:string;processed_unit:string;provenance?:string};
export type RunData={manifest:RunManifest;result:Record<string,any>;metrics:{raw?:Metrics;refined?:Metrics};predictions:Row[];profiles:Record<string,any>[];reference:Record<string,any>[];biomarkers:Row[];rawReport:Row[];refinedReport:Row[];confusion:Row[];refinedConfusion:Row[];calibration:Record<string,any>;calibrationBins:Row[];riskCoverage:Row[];training:Row[];signals:Record<string,SignalData>;artifacts:Artifact[]};
export type Imported={id:string;name:string;path:string;bytes:number;source:string};
export type Connection={state:string;message:string;gpu?:string;python?:string;session?:string;checks?:Record<string,boolean>;packages?:Record<string,string|null>;sessions?:{name:string;accelerator:string}[];distributions?:string[]};
export type AuthPrompt={requestId:string;kind:'code'|'continue';message:string;urls:string[]};
export type Bootstrap={settings:Settings;runs:RunManifest[];baseline:RunData|null;model:Record<string,any>;layers:Row[];dataset:Record<string,any>;recordings:Row[];distributions:Row[];preprocessing:Record<string,any>;transition:Record<string,any>;rules:Record<string,any>;exampleSignal:SignalData|null;stages:string[];connection:Connection;logs:{time:string;message:string}[];desktop:boolean;imports:Imported[];prompt?:AuthPrompt|null};
export type DriveItem={name:string;path:string;directory:boolean;bytes:number};
export type Api={bootstrap:()=>Promise<Bootstrap>;settings:()=>Promise<Settings>;saveSettings:(s:Settings)=>Promise<Settings>;discover:()=>Promise<{distributions:string[];sessions:{name:string;accelerator:string}[];cliPath:string}>;connect:()=>Promise<Connection>;mountDrive:()=>Promise<Connection>;prepareRuntime:()=>Promise<Connection>;browseDrive:(folder:string)=>Promise<{folder:string;items:DriveItem[]}>;startRun:(options:Record<string,unknown>)=>Promise<RunManifest>;cancelRun:(id:string)=>Promise<unknown>;recoverRun:(id:string)=>Promise<RunManifest>;run:(id:string)=>Promise<RunData>;runs:()=>Promise<RunManifest[]>;importFiles:()=>Promise<Imported[]>;artifacts:(id:string)=>Promise<Artifact[]>;artifactText:(id:string,file:string)=>Promise<string>;exportRun:(id:string,format:string,artifact?:string)=>Promise<string|null>;exportPdf:(id:string)=>Promise<string|null>;openArtifact:(id:string,file:string)=>Promise<unknown>;openExternal:(url:string)=>Promise<unknown>;authReply:(value:string)=>Promise<unknown>;signal:(id:string,recording:string,epoch:number)=>Promise<SignalData|null>;onEvent:(callback:(event:any)=>void)=>()=>void};
declare global {interface Window {sleep?:Api}}
