import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const runtime='C:/Users/Rikin Parekh/.cache/codex-runtimes/codex-primary-runtime/dependencies';
process.env.RUNTIME_NODE_MODULES=runtime+'/node/node_modules';
const {PresentationFile,FileBlob}=await import(pathToFileURL(runtime+'/node/node_modules/@oai/artifact-tool/dist/artifact_tool.mjs').href);
const ROOT=path.resolve('.'),OUT=path.join(ROOT,'refinement_artifacts'),D=path.join(OUT,'verified');
const read=async name=>JSON.parse(await fs.readFile(path.join(D,name),'utf8'));
const result=await read('final_results.json'),metrics=await read('overall_metrics.json'),profiles=await read('subject_profiles.json'),refs=await read('reference_stats.json'),model=await read('refinement_model.json');
const raw=metrics.raw,ref=metrics.refined;
const pct=v=>(100*v).toFixed(2)+'%',num=(v,d=2)=>v===null?'Unavailable':Number(v).toFixed(d);
const finalProfiles=profiles.filter(p=>p.source==='refined');
const identity='Rikin Parekh · Om Ahuja\n23BIT044 · 23BIT014\nGuide: Dr. Santosh Sathpathy\nInformation and Communication Technology\nPandit Deendayal Energy University';
const C={bg:'#F5FAFC',ink:'#102E49',muted:'#526977',accent:'#18A69B',light:'#E8F2F5',white:'#FFFFFF'};
const desc='Reference boundaries describe the HMC training cohort; profile levels are descriptive domain counts.';
const specs=[
 {title:'EEG Sleep Classification and Reference-Based Sleep-Health Profiling',cover:true,body:['Existing evidential Transformer with targeted N1/N2 spectral refinement',identity,'Verified notebook reproduction · 7 October 2026']},
 {title:'Problem and project scope',body:['Classify each 30-second EEG epoch as Wake, N1, N2, N3, or REM.','Baseline confusion: 506 true N2 epochs were predicted N1.','Extend the retained classifier with spectral refinement and recording-level descriptive profiles.','HMC comparisons are research reference comparisons, not diagnostic conclusions.']},
 {title:'Implemented project objectives',body:['Retain the five-stage evidential Transformer and its uncertainty output.','Refine Transformer-predicted N1/N2 using nine EEG spectral features.','Calculate architecture metrics and aggregate spectral biomarkers.','Compare with the 16-recording training reference and display four-domain deviation profiles.']},
 {title:'HMC Sleep Staging Database v1.1',body:['151 whole-night PSG recordings; 85 male and 66 female.','Mean age: 53.9 ± 15.4 years.','A heterogeneous population referred for PSG examinations.','The project uses 24 recordings and four EEG channels sampled originally at 256 Hz.'],note:'Dataset source: https://physionet.org/content/hmc-sleep-staging/1.1/'},
 {title:'Recording-wise experimental split',table:[['Partition','Recordings','Stored epochs'],['Training','16','15,216'],['Validation','4','3,619'],['Testing','4','3,109'],['Total','24','21,944']],foot:'Test IDs: SN001, SN004, SN009, SN022. SN identifiers name recordings; partitions are disjoint.'},
 {title:'Evaluation scope and SN001 segment',body:['Current notebook: 3,109 test epochs, including SN001’s stored 190 epochs (95 minutes).','Earlier EDF alignment audit: SN001 reconstructed to 854 epochs; test total 3,773.','The 55.45% → 59.34% comparison belongs to the current stored-input experiment.','SN001’s segment duration and onset do not establish whole-night sleep-health measurements.']},
 {title:'EEG preprocessing and model input',body:['Channels: EEG F4-M1, EEG C4-M1, EEG O2-M1, EEG C3-M2.','Actual preprocessing order: 50 Hz notch at the original rate, 0.3–35 Hz bandpass, resample to 100 Hz.','Complete 30-second epochs; per-epoch, per-channel normalization.','Each input epoch: 4 channels × 3,000 samples. Apply the notch before 100 Hz resampling.'],image:'eeg'},
 {title:'Retained Fast SCFormer-U architecture',body:['4 × 3,000 EEG → Conv1D 64 (kernel 7, stride 4) → Conv1D 128 (kernel 5, stride 4)','Self-attention: 4 heads, key dimension 16; residual normalization and feed-forward layers','Bidirectional LSTM: 64 units per direction; pooling and dense evidence head','Five softplus evidence outputs; 226,309 total parameters. Attention and recurrence operate within the epoch.']},
 {title:'Role of the retained components',table:[['Component','Role'],['CNN encoder','Local EEG patterns and temporal downsampling'],['Self-attention','Relations between positions within each epoch'],['BiLSTM','Downsampled within-epoch sequence'],['Evidence head','Five-class Dirichlet evidence'],['Spectral refinement','Independent classifier for N1/N2 candidates']]},
 {title:'Evidential probabilities and uncertainty',body:['alpha_k = evidence_k + 1','P_k = alpha_k / sum(alpha)','Uncertainty = 5 / sum(alpha)','Refinement changes the selected N1/N2 label. Transformer probabilities and uncertainty still refer to the original five-stage output.']},
 {title:'Retained training configuration',table:[['Setting','Existing Transformer'],['Optimizer / learning rate','Adam / 0.0001'],['Batch size / maximum epochs','128 / 10'],['Validation-selected checkpoint','Epoch 9'],['Class weighting','Training labels only'],['Architecture replacement','None']],foot:'The refinement audit loads the saved checkpoint; it does not retrain the Transformer.'},
 {title:'Original Transformer performance',table:[['Metric','Stored-input test set'],['Accuracy',pct(raw.accuracy)],['Macro F1',pct(raw.macro_f1)],['N1 F1','36.60%'],['N2 F1','57.12%'],['Evaluated epochs','3,109']],foot:'Same labels and epochs are used for the baseline/refinement comparison.'},
 {title:'Baseline confusion matrix',image:'raw_confusion_matrix.png',foot:'Largest N2 error: 506 N2 epochs predicted N1. Rows are true labels; columns are predictions.'},
 {title:'Nine EEG features for N1/N2 refinement',table:[['Feature group','Features'],['Relative band power','Delta, Theta, Alpha, Sigma, Beta'],['Ratios to Delta','Sigma/Delta, Theta/Delta, Alpha/Delta, Beta/Delta'],['Frequency bands (Hz)','0.5–4; 4–8; 8–12; 12–16; 16–30'],['Candidate gate','Transformer predicts N1 or N2']],foot:'These are project feature boundaries, not AASM staging definitions. Sigma power does not measure spindle density.'},
 {title:'Welch spectral extraction',body:['Welch PSD per channel: 100 Hz, 400-sample windows (4 seconds), 200-sample overlap.','Integrate each band with a lower-inclusive, upper-exclusive frequency mask.','Average band powers across the four channels before computing relative powers and ratios.','Relative power denominator: measured total power in 0.5–30 Hz. Aggregate epoch features by arithmetic mean per recording.']},
 {title:'Relative powers and Delta ratios',body:['Relative band power = mean channel band power / mean channel total power','Band/Delta ratio = mean channel band power / mean channel Delta power','Delta is a project feature-engineering reference, not a mandatory denominator.','Normalized EEG powers are spectral features; do not describe them as calibrated absolute physical power.']},
 {title:'Training and inference gates',body:['Fit the refiner only on training epochs where the true stage AND the Transformer prediction are N1/N2.','Training subset: 1,278 N1 and 4,588 N2 epochs; 5,866 total.','StandardScaler → LogisticRegression(class_weight="balanced", max_iter=2000, random_state=42).','At inference, gate by the Transformer prediction only. Ground truth is never used to route test epochs.']},
 {title:'Standardized logistic regression coefficients',table:[['Feature','Coefficient toward N2'],...model.feature_order.map((f,i)=>[f.replaceAll('_',' '),num(model.coefficients[i],3)])],foot:'Multivariate coefficients depend on correlated features and standardization; do not read them as isolated physiological rules.',small:true},
 {title:'Effect of targeted N1/N2 refinement',image:'performance_comparison.png',foot:'Accuracy +3.89 pp; macro F1 +2.10 pp using unrounded values. N1 F1 +4.03 pp; N2 F1 +6.45 pp.'},
 {title:'Which predictions changed?',table:[['Outcome','Epochs'],['Unchanged','2,871'],['Corrected','154'],['Wrong to wrong','51'],['Degraded','33'],['Total changed','238']],foot:'W, N3 and REM predictions are retained. Epochs truly in those stages can still enter refinement if originally predicted N1/N2.'},
 {title:'Performance by test recording',table:[['Recording','Epochs','Baseline accuracy','Refined accuracy'],['SN001','190','46.84%','48.42%'],['SN004','1,016','56.79%','64.07%'],['SN009','901','61.27%','64.48%'],['SN022','1,002','50.50%','52.00%']],foot:'The SN001 evaluation covers 95 minutes. No whole-night performance or external cohort validation is implied.'},
 {title:'Refined confusion matrix',image:'refined_confusion_matrix.png',foot:'N2→N1 errors: 506 → 379. All true N1/N2 epochs: accuracy 53.75% → 60.95% (1,680 epochs).'},
 {title:'Original and refined hypnogram — SN009',image:'hypnogram_SN009.png',foot:'Targeted N1/N2 changes retain the other predicted stages and the recording order.'},
 {title:'Sleep architecture measurements',table:[['Metric','Definition'],['TST','N1 + N2 + N3 + REM time'],['Sleep efficiency','100 × TST / evaluated recording duration'],['Stage percentages','100 × stage sleep time / TST'],['WASO','Wake time after first sleep to sequence end'],['Fragmentation','All stage transitions / TST hours']],foot:'Recording duration is an evaluated-window measure. Contiguous timing is assumed for the notebook NPZ sequences.'},
 {title:'Sleep duration and efficiency',body:['Each stored epoch contributes 0.5 minutes. Wake is excluded from TST.','Sleep efficiency uses the duration of the evaluated sequence, not independently verified time in bed.','N1/N2 refinement cannot change TST or efficiency because both labels are sleep.','SN001’s 91.5 minutes predicted sleep in a 95-minute segment must not be treated as whole-night sleep duration.']},
 {title:'Sleep initiation and Wake after sleep onset',body:['SOL = index of first non-Wake epoch × 0.5 minutes.','WASO includes every Wake epoch after onset, including Wake at the end of this notebook’s sequence.','REM latency = time from first sleep epoch to first REM epoch.','No sleep or no REM makes the corresponding metric unavailable. Segment onset is relative to the segment, not lights-out.']},
 {title:'Stage percentages and fragmentation',body:['N1%, N2%, N3%, REM% use TST as the denominator and sum to approximately 100%.','Awakenings count non-Wake → Wake transitions after first sleep.','Stage transitions count every adjacent pair whose labels differ.','Fragmentation = stage transitions / TST hours. This project-defined index is not EEG micro-arousal scoring.']},
 {title:'Recording-level EEG spectral biomarkers',table:[['Recording','Delta','Theta','Alpha','Sigma','Beta'],...finalProfiles.map(p=>[p.subject_id,...['delta','theta','alpha','sigma','beta'].map(b=>num(p[b+'_relative'],4))])],foot:'Means of per-epoch relative features across all evaluated epochs, including Wake. Four band/Delta ratios are also retained.'},
 {title:'Master feature matrix and training reference',body:['Test matrix: 4 rows × 23 columns = subject ID + 22 numeric fields.','Training reference matrix: 16 rows × 23 columns.','Numeric fields: 13 recording/architecture fields + nine EEG spectral features.','Deviation analysis excludes recording_minutes: 21 compared fields. Ten architecture metrics feed the four domain statuses.']},
 {title:'Training reference — architecture',table:[['Metric','Mean','SD','P10','P90'],...refs.filter(r=>['TST_minutes','sleep_efficiency_percent','sleep_onset_latency_min','WASO_minutes','N1_percent','N2_percent','N3_percent','REM_percent'].includes(r.feature)).map(r=>[r.feature.replaceAll('_',' '),num(r.mean),num(r.std),num(r.p10),num(r.p90)])],foot:'Sample SD uses ddof=1; empirical quantiles use linear interpolation. Reference architecture uses fitted training-recording predictions.',small:true},
 {title:'Training reference — EEG features',table:[['EEG feature','Mean','SD','P10','P90'],...refs.filter(r=>model.feature_order.includes(r.feature)).map(r=>[r.feature.replaceAll('_',' '),num(r.mean,4),num(r.std,4),num(r.p10,4),num(r.p90,4)])],foot:'Dataset-derived descriptive boundaries from 16 training recordings. No healthy normative cohort was established.',small:true},
 {title:'Z-scores and P10/P90 regions',body:['z = (recording value − reference mean) / reference SD','LOW: below P10; NORMAL: P10 through P90; HIGH: above P90.','Z-score measures magnitude and direction; percentile regions provide a categorical reference comparison.','NORMAL means within the dataset interval. LOW/HIGH do not mean medically bad/good. Equality at either boundary stays within reference.']},
 {title:'Four sleep-health domains',table:[['Domain','Metrics used'],['Duration','TST'],['Continuity','Sleep efficiency, WASO, awakenings, fragmentation'],['Initiation','SOL'],['Architecture','N1%, N2%, N3%, REM%']],foot:'Any LOW or HIGH metric makes its domain DEVIATED. EEG deviations are shown separately and do not determine domain counts.'},
 {title:'Overall descriptive profile levels',table:[['Deviated domains','Profile'],['0','Within Reference'],['1','Mild Deviation'],['2','Moderate Deviation'],['3 or 4','High Deviation']],foot:desc},
 {title:'Test-recording domain profiles',table:[['Recording','Duration','Continuity','Initiation','Architecture','Overall'],...finalProfiles.map(p=>[p.subject_id,...['Sleep_Duration','Sleep_Continuity','Sleep_Initiation','Sleep_Architecture'].map(d=>p[d+'_status']==='DEVIATED'?'Deviated':'Within ref.'),p.sleep_health_deviation_profile])],foot:'SN001: segment profile. HMC reference deviations are neither disease-risk predictions nor validated severity levels.',small:true},
 {title:'Interactive Sleep Studio dashboard',image:'dashboard.png',foot:'Select SN001/SN004/SN009/SN022. Inspect domains, sleep architecture, nine EEG features, z-scores, P10/P90, and source artifacts.'},
 {title:'Complete implemented pipeline',body:['Raw EEG → existing preprocessing → evidential Transformer → targeted N1/N2 spectral refinement','Refined hypnogram → sleep architecture; EEG → spectral biomarkers','Recording feature matrix → 16-recording training reference → z-scores + P10/P90 regions','Four domain statuses → descriptive overall deviation profile → interactive dashboard and report exports']},
 {title:'Limitations and unimplemented extensions',body:['No explicit spindle detector, dedicated formal SWA metric, or spectral edge frequency.','No clinically validated normative ranges, disease prediction, or diagnostic severity classification.','No documented repeated-night participant mapping for true longitudinal personalization.','Small clinical reference (16 recordings), assumed NPZ continuity, in-sample reference architecture, and a partial SN001 input.']},
 {title:'Model uncertainty and profile deviation',table:[['Quantity','Question answered','Source'],['Transformer uncertainty','How much evidence supports this epoch classification?','5 / sum(alpha)'],['Sleep-health deviation','How does this recording compare with the training reference?','z-score and P10/P90'],['Overall profile','How many architecture domains deviate?','0–4 domain count']],foot:'The new label refinement does not recalibrate Transformer probabilities or provide uncertainty for the logistic classifier.'},
 {title:'Project outcome',body:[`The retained Transformer’s test accuracy improves from ${pct(raw.accuracy)} to ${pct(ref.accuracy)} with targeted spectral refinement.`,`Macro F1 improves from ${pct(raw.macro_f1)} to ${pct(ref.macro_f1)}; N1 and N2 remain challenging.`,`The dashboard combines architecture, EEG spectral features, reference deviations, and four-domain profiles.`,desc]},
 {title:'Sources and reproducibility',body:['Implementation: Biomarker_N1_N2_Refinement.ipynb, new pipeline cells 1–46.','Independent Colab reproduction: HMC-N1N2-20261007; saved checkpoint and stored NPZ inputs.','HMC v1.1: Alvarez-Estevez & Rijsman (2022), DOI 10.13026/t79q-fr32.','Full feature tables, refiner scaler/coefficients, per-epoch outputs, hashes, and checks are in refinement_artifacts/verified.'],note:'https://physionet.org/content/hmc-sleep-staging/1.1/\nIndependent reproduction script: refinement_artifacts/reproduce.py'}
];
function text(slide,value,x,y,w,h,size=25,bold=false,color=C.ink){const shape=slide.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});shape.text=value;shape.text.style={typeface:'Arial',fontSize:size,bold,color,autoFit:'none'};return shape;}
function rect(slide,x,y,w,h,fill){return slide.shapes.add({geometry:'rect',position:{left:x,top:y,width:w,height:h},fill,line:{fill:'none',width:0}});}
async function fill(slide,spec,index,total,w,h){
 slide.shapes.deleteAll();for(const k of ['images','tables','charts'])for(const object of [...slide[k].items])slide[k].deleteById(object.id);
 slide.background.fill=C.bg;
 const sx=w/1280,sy=h/720;const T=(v,x,y,ww,hh,z=25,b=false,c=C.ink)=>text(slide,v,x*sx,y*sy,ww*sx,hh*sy,z*sx,b,c);
 rect(slide,0,0,12*sx,h,C.accent);
 if(spec.cover){T('FINAL PROJECT REPORT',64,50,1150,35,17,true,C.accent);T(spec.title,64,122,1140,150,42,true);T(spec.body[0],64,290,1120,70,24,false,C.muted);T(identity,64,422,920,172,21);T(spec.body[2],64,644,1100,40,17,false,C.muted);}
 else{
 T(spec.title,62,34,1150,90,33,true);rect(slide,62*sx,130*sy,1150*sx,2*sy,C.accent);
 if(spec.table){const values=spec.table;const top=165,rows=values.length;const height=Math.min(430,rows*(spec.small?39:60));const table=slide.tables.add({rows,columns:values[0].length,left:64*sx,top:top*sy,width:1144*sx,height:height*sy,values:values.map(row=>row.map(String))});for(let i=0;i<rows;i++)for(let j=0;j<values[0].length;j++){const cell=table.getCell(i,j);cell.fill=i===0?C.ink:(i%2?C.white:C.light);cell.text.style={typeface:'Arial',fontSize:(spec.small?19:23)*sx,bold:i===0,color:i===0?C.white:C.ink,autoFit:'shrinkText'};}}
 else if(spec.image&&spec.image!=='eeg'){
 const file=path.join(D,spec.image);try{slide.images.add({blob:await fs.readFile(file),contentType:'image/png',alt:spec.title,fit:'contain',position:{left:62*sx,top:152*sy,width:1150*sx,height:430*sy}});}catch(e){if(spec.image==='dashboard.png')throw e;throw new Error('Missing required plot '+file);}
 }else{
 const body=spec.body||[];const gap=spec.image==='eeg'?82:102;body.forEach((v,i)=>{rect(slide,64*sx,(171+i*gap)*sy,5*sx,40*sy,C.accent);T(v,88,162+i*gap,1110,gap-10,25);});
 }
 if(spec.foot)T(spec.foot,64,612,1140,55,17,false,C.muted);
 T('Source: '+(spec.note?.startsWith('Dataset')?'PhysioNet HMC v1.1':'HMC-N1N2-20261007 · notebook and reproduced artifacts'),64,685,1080,22,12,false,C.muted);
 T(String(index+1).padStart(2,'0')+' / '+total,1175,685,70,22,12,false,C.muted);
 }
 slide.speakerNotes.textFrame.setText((spec.note||'Source: Biomarker_N1_N2_Refinement.ipynb cells 1–46; independent reproduction HMC-N1N2-20261007.')+'\n'+(spec.foot||'')+'\n'+result.limitations.join('\n'));
}
const short=[specs[0],{...specs[4],title:'HMC data and EEG input',foot:'HMC v1.1: 151 clinical recordings; subset 24. Four channels, 100 Hz, 30 s (4 × 3,000). SN001: 95-minute segment.'},specs[7],specs[13],specs[16],specs[18],specs[23],{title:'Training reference and four-domain profiles',body:['Reference: 16 training recordings; test matrix: ID + 22 numeric fields. Compare 21 fields, excluding duration of the evaluated window.','z = (value − mean) / sample SD. Below P10 → LOW; P10–P90 → NORMAL; above P90 → HIGH.','Domains: Duration (TST); Continuity (efficiency, WASO, awakenings, fragmentation); Initiation (SOL); Architecture (N1/N2/N3/REM %).','Any out-of-range metric marks its domain. 0 / 1 / 2 / 3–4 deviated domains → Within Reference / Mild / Moderate / High Deviation.'],foot:'Dataset reference, not healthy norms. EEG deviations are displayed separately; profile levels are descriptive counts.'},specs[34],specs[35],specs[36],specs[37]];
const {finalizePresentation}=await import(pathToFileURL('C:/Users/Rikin Parekh/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.11814/skills/presentations/container_tools/artifact_tool_utils.mjs').href);
for(const name of ['final_sleep_stage_project_presentation.pptx','sleep_stage_project_12_slides.pptx','mid.original_backup.pptx']){
 const presentation=await PresentationFile.importPptx(await FileBlob.load(path.join(OUT,'originals',name)));
 const selected=name.includes('12_slides')?short:specs;
 if(presentation.slides.items.length!==selected.length)throw new Error('Unexpected source slide count');
 for(let i=0;i<selected.length;i++){const slide=presentation.slides.items[i];await fill(slide,selected[i],i,selected.length,slide.frame.width,slide.frame.height);}
 const staging=path.join(OUT,'build',name);await fs.mkdir(path.dirname(staging),{recursive:true});
 await(await PresentationFile.exportPptx(presentation)).save(staging);
 const validated=path.join(OUT,'build','validated-'+name);
 await fs.rm(validated,{force:true});
 const skill='C:/Users/Rikin Parekh/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.11814/skills/presentations';
 const frame=presentation.slides.items[0].frame;
 await fs.mkdir(path.join(OUT,'validation'),{recursive:true});
 await finalizePresentation({workspaceDir:ROOT,candidatePath:staging,finalPath:validated,pythonExecutable:runtime+'/python/python.exe',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu',`${Math.round(frame.width*9525)},${Math.round(frame.height*9525)}`],fontPolicy:{basis:'design',families:['Arial']},verifyArtifactToolImport:true,receiptPath:path.join(OUT,'validation',name+'.validation.json')});
 await fs.copyFile(validated,path.join(ROOT,name));console.log('Updated '+name+' ('+selected.length+' slides)');
}
