const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {Store,csv,confined,validateSettings}=require('../electron/store.cjs');const {validateOptions,remotePath,py}=require('../electron/service.cjs');const {report}=require('../electron/report.cjs');
const project=path.resolve(__dirname,'../..');
test('CSV parsing preserves quoted commas, multiline fields, escaped quotes, zero and missing values',()=>{const rows=csv('id,note,count,empty\r\na,"comma, line\nnext ""word""",0,\r\n');assert.deepEqual(rows,[{id:'a',note:'comma, line\nnext "word"',count:0,empty:null}]);});
test('artifact paths reject traversal and absolute paths',()=>{assert.throws(()=>confined(project,'../../etc/passwd'));assert.throws(()=>confined(project,'/etc/passwd'));assert.equal(confined(project,'ppt_artifacts/final_results.json'),path.join(project,'ppt_artifacts/final_results.json'));});
test('artifact symlinks cannot escape a run',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'sleep-path-')),outside=fs.mkdtempSync(path.join(os.tmpdir(),'sleep-outside-'));try{fs.writeFileSync(path.join(outside,'artifact.txt'),'outside');fs.symlinkSync(outside,path.join(root,'escape'),'junction');assert.throws(()=>confined(root,'escape/artifact.txt'));}finally{fs.rmSync(root,{recursive:true,force:true});fs.rmSync(outside,{recursive:true,force:true});}});
test('settings only accept intended values and paths',()=>{assert.throws(()=>validateSettings({session:'x; rm'}));assert.throws(()=>validateSettings({theme:'invalid'}));assert.throws(()=>validateSettings({checkpointPath:'/content/../etc/passwd'}));assert.throws(()=>validateSettings({persistDrive:'yes'}));assert.deepEqual(validateSettings({theme:'light',unknown:'ignored'}),{theme:'light'});});
test('job options reject invalid numerical ranges and types',()=>{assert.throws(()=>validateOptions({batchSize:0}));assert.throws(()=>validateOptions({learningRate:NaN}));assert.throws(()=>validateOptions({refinement:'false'}));assert.throws(()=>validateOptions({epochs:101}));assert.equal(validateOptions({}).batchSize,128);assert.throws(()=>remotePath('/content/drive/../private'));assert.ok(py({name:'"; dangerous',enabled:true}).startsWith('json.loads('));});
test('the actual baseline contains all 3109 epochs and separate profile sources',()=>{const store=new Store(project,path.join(os.tmpdir(),'sleep-test-unused'));const value=store.bootstrap();assert.equal(value.baseline.predictions.length,3109);assert.equal(value.dataset.recordings,24);assert.equal(value.model.parameters,226309);assert.equal(value.baseline.biomarkers.length,12);assert.equal(value.baseline.metrics.refined.accuracy,0.5934384046317144);assert.equal(value.exampleSignal.epoch_index,10);assert.ok(value.baseline.artifacts.some(x=>x.path==='refinement_model.json'));});
test('run metadata round-trips atomically and invalid IDs cannot read other files',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'sleep-store-'));try{const store=new Store(project,root);store.init();store.saveRun({id:'run-test',createdAt:'2026-10-07',status:'queued'});assert.equal(store.manifest('run-test').status,'queued');assert.throws(()=>store.manifest('../settings'));assert.equal(store.runs().length,2);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('PDF report escapes artifact names and run descriptions',()=>{const store=new Store(project,os.tmpdir());const value=store.run('baseline');value.manifest.name='<script>alert(1)</script>';const html=report(value);assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>'));assert.ok(html.includes('0.5934'));});

test('offline ZIP export preserves the source artifact and run provenance',()=>{const {zipSync,unzipSync}=require('fflate');const store=new Store(project,os.tmpdir());const source=fs.readFileSync(store.artifactFile('baseline','overall_metrics.json'));const zipped=zipSync({'overall_metrics.json':new Uint8Array(source),'desktop_run.json':new Uint8Array(Buffer.from(JSON.stringify(store.manifest('baseline'))))});const value=unzipSync(zipped);assert.deepEqual(Buffer.from(value['overall_metrics.json']),source);assert.equal(JSON.parse(Buffer.from(value['desktop_run.json']).toString()).sourceRun,'HMC-N1N2-20261007');});
