const escape = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function table(rows,columns) { return `<table><thead><tr>${columns.map(c=>`<th>${escape(c)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map(c=>`<td>${escape(typeof row[c]==='number'?Math.round(row[c]*10000)/10000:row[c])}</td>`).join('')}</tr>`).join('')}</tbody></table>`; }
function report(run,images=[]) {
 const metrics=run.metrics || {}; const entries=['raw','refined'].filter(x=>metrics[x]).map(condition=>({condition,...metrics[condition]}));
 const profiles=(run.profiles||[]).filter(p=>p.source==='refined'||(!metrics.refined&&p.source==='raw'));
 return `<!doctype html><html><head><meta charset="utf-8"><title>Sleep Studio report</title><style>body{font:12px Arial,sans-serif;color:#162c30;margin:36px}h1{font-size:30px;color:#146b63}h2{margin-top:26px;font-size:17px}p{line-height:1.6}table{width:100%;border-collapse:collapse;margin:12px 0}th,td{text-align:left;border-bottom:1px solid #dae3e4;padding:8px;font-size:10px}th{background:#f1f6f5}.muted{color:#637779}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:10px}.stage{display:inline-block;margin-right:12px;padding:5px;background:#edf5f3}.plot{break-inside:avoid;page-break-inside:avoid;margin:24px 0}.plot img{width:100%;max-height:400px;object-fit:contain}.plot h2{font-size:14px}</style></head><body>
 <p class="muted">SLEEP STUDIO / EEG ANALYSIS</p><h1>${escape(run.manifest.name||run.manifest.id)}</h1>
 <p>Run: ${escape(run.manifest.sourceRun||run.manifest.id)}<br>Created: ${escape(run.manifest.createdAt)}<br>Status: ${escape(run.manifest.status)}<br>Checkpoint SHA256: ${escape(run.result.checkpoint_sha256||run.manifest.checkpoint?.sha256||'Recorded in manifest')}</p>
 <h2>Classification performance</h2>${entries.length?table(entries,['condition','accuracy','balanced_accuracy','macro_f1','weighted_f1','cohen_kappa','test_epochs']):'<p>Ground-truth evaluation is unavailable for this run.</p>'}
 <h2>Descriptive sleep-health profiles</h2>${table(profiles,['subject_id','sleep_health_deviation_profile','deviated_domain_count','Sleep_Duration_status','Sleep_Continuity_status','Sleep_Initiation_status','Sleep_Architecture_status'])}
 <p class="muted">Reference: 16 HMC training recordings, a heterogeneous clinical population. Levels count deviated domains; they are not clinical severity, disease-risk predictions, or diagnoses. Stage uncertainty belongs to the original Transformer output. Stored SN001 covers 190 epochs (95 minutes); its profile describes a segment rather than a complete night.</p>
 ${profiles.map(p=>`<h2>${escape(p.subject_id)}: architecture and EEG biomarkers</h2><p>${escape(p.scope)}</p>${table(Object.entries(p.deviations||{}).map(([feature,d])=>({feature,...d})),['feature','value','mean','std','p10','p90','z','flag'])}`).join('')}
 <p>Stage percentages use TST. WASO includes Wake epochs after first sleep through the end of the evaluated sequence. Fragmentation is all stage transitions per TST hour. EEG relative power uses 0.5-30 Hz total power; Welch uses 4-second windows and 2-second overlap. Sigma power does not measure spindle density. LOW/NORMAL/HIGH indicate position relative to P10/P90 only.</p>
 ${images.map(image=>`<div class="plot"><h2>${escape(image.title)}</h2><img src="${escape(image.data)}" alt="${escape(image.title)}"/></div>`).join('')}<h2>Configuration and provenance</h2><pre>${escape(JSON.stringify(run.manifest.settings||run.result,null,2))}</pre>
 <h2>Artifacts</h2>${table(run.artifacts,['path','bytes'])}</body></html>`;
}
module.exports={report,escape};
